config/routes.rb
Rails.application.routes.draw do

  # post 'comments', to: 'comments#create'

  # delete 'comments/:id', to: 'comments#destroy'
resources :comments, only: [:create, :destroy]

	# loging form 
  get '/login', to: 'login#new'
  # check to see if we have a user, then set session[:user_id]
  post '/login', to: 'login#create'
  # logout
  delete '/logout', to: 'login#destroy'

  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/', to: 'home#index'

	get '/goodbye', to: 'greeting#goodbye'

	get '/hello', to: 'greeting#hello'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	validates :title, presence: { message: "feels lonely!"}
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :name, presence: true
	validates :email, uniqueness: true
	

	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user, :send_to_login_unless_logged_in

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def send_to_login_unless_logged_in
  
  	if @current_user.nil?
  		redirect_to login_path, notice: "You must log in before proceeding." 
  	
   end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		# params[:comment]
		comment = @current_user.comments.create(comment_params)
		if comment.persisted?
			redirect_to post_path(comment.post), notice: "We saved your comment."
		else
			redirect_to post_path(comment.post), notice: "We couldnt save your comment."
		end
	end

	def destroy
		comment = Comment.find(params[:id])
		if comment.destroy!
			redirect_to post_path(comment.post.id), notice: "We deleted your comment."
		end
	end

	private

	def comment_params
		params.fetch(:comment, {}).permit(:post_id, :content)
	end


end

app/controllers/greeting_controller.rb
class GreetingController < ApplicationController
	def hello
	end
	def goodbye
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end


end

# CRUD
# Show - One element of a certain type
# index - All the elements of a cdrtain type
# edit - render a page to allow you to change element
# update - 
# destroy! - 

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :send_to_login_unless_logged_in
  def new
  end

  def create
  	user = User.find_by(email: params[:email])

  	respond_to do |format|
      if user && user.authenticate(params[:password])
  	# if user && user.authenticate(params[:password])
  		  session[:user_id] = user.id
  		  format.html { redirect_to posts_path, notice: 
  		  	"#{user.first_name}, you were logged in successfully!"}

  	else
  		@error = "Your email and password is strongly not correct."
  		  format.html { render :new }
    end
  	end
  
	end
  def destroy
  	session[:user_id] = nil
  	respond_to do |format|
  		format.html { redirect_to login_path, notice: 'You have been logged out, you loser!'}
  	 end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :only_allow_current_user, only: [:edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    # @posts = @current_user.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #1. MAKE NEW POSTS THROUGH CURRENT USER
    @post = @current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private

    def only_allow_current_user
      redirect_to @post unless @current_user == @post.user
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      # 2. REMOVED USER_ID from PERMITTED PARAMS
      params.fetch(:post, {}).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/greeting/goodbye.html.erb
<h1> Goodbye </h1>

app/views/greeting/hello.html.erb
<h1> Hello! </h1>

app/views/home/index.html.erb
<h1> You are here !</h1>
<h2> Where have you been?</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newrail</title>
    <title><%= yield(:title) %></title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%=image_tag "metalshoe.jpg", class:"my-img"%>
  </head>

  <body>


  	<div> 

  		<% if @current_user.present? %>
  		<h3><%= @current_user.first_name %> is logged in </h3>
  		<td><%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure you want to logout?' } %></td>
  		<% end %>
  	</div>


    <%= yield %>
  </body>
</html>

app/views/login/create.html.erb
<h1>Login#create</h1>
<p>Find me in app/views/login/create.html.erb</p>

app/views/login/destroy.html.erb
<h1>Login#destroy</h1>
<p>Find me in app/views/login/destroy.html.erb</p>

app/views/login/new.html.erb
<h1>Login</h1>



<%= form_tag("/login", method: "post") do %>
 	<fieldset>
 <% if @error.present? %>
      <div id="error_explanation">
        <h2> An error prohibited this post from being saved:</h2>
        <ul>
          <li><%= @error %></li>
        </ul>
      </div>
    <% end %>

		<%= label_tag :email %>
		<%= text_field_tag :email %>

		<%= label_tag :password %>
		<%= password_field_tag :password %>
		<br>
		<br>
		<%= submit_tag "Submit" %>
 	</fieldset>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <fieldset>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <% if post.errors.messages[:title].any? %>
      <div class="error">
        <%= post.errors.messages[:title][0] %>
      </div>
    <% end %>

  <%= f.label :content %>
  <%= f.text_area :content, size: "211x12" %>


  <div class="actions">
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<%=image_tag "blog.jpg", class:"img-responsive"%>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.user.first_name %></td>
        <td><%= post.user.password %></td>
        <td><%= link_to 'Show', post %></td>

        <% if @current_user == post.user %>

          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<blockquote class="blockquote-reverse">
  
<h1> <%= @post.title %> </h1>

</blockquote>
<blockquote>
  
  <small><cite title="Source Title"></cite></small>

<h4> By: <%= @post.user.first_name %> </h4>

<p> <%=@post.content %> </p>
</blockquote>
<h2>Comments</h2>

<% @post.comments.each do |comment| %>
<blockquote>	
	<p><%= comment.content %></p>
	<h4> By: <%= comment.user.first_name %> </h4>
</blockquote>
	<% if @current_user == comment.user %>

          
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %></td>
          
    <% end %>
<% end %>

<%= form_for(@post.comments.new) do |f| %>
	
	<%=f.hidden_field :post_id, value: @post.id %>
	<%=f.label :content, "Add a comment" %>
	<%=f.text_area :content, size: "80x4" %>
	<br>
	<%=f.submit "Submit Post" %>

<% end %>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <fieldset>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <%= f.label :first_name %>
  <%= f.text_field :first_name, size: "100x6" %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name, size: "100x6" %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.text_field :password %>


  <div class="actions">
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @user.first_name %> <%= @user.last_name %></h2>

<h4> <%= @user.email %> </h4>

<h2><%= @user.first_name %>'s Posts </h2>

<% @user.posts.each do |post| %>
	<p><%= link_to post.title, post_path(post) %></p>
<% end %>

<h2><%= @user.first_name %>'s Comments</h2>

<% @user.comments.each do |comment| %>
	<p><%= comment.content %></p>
	<h4> By: <%= comment.user.first_name %> </h4>
	

<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>